[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/data.json"
  to = "/index.html"
  status = 404
  force = true

[[redirects]]
  from = "/server.js"
  to = "/index.html"
  status = 404
  force = true

[[redirects]]
  from = "/server-error.txt"
  to = "/index.html"
  status = 404
  force = true